auxlib.o: auxlib.cpp auxlib.h
oc.o: oc.cpp auxlib.h stringset.h lyutils.h astree.h auxlib.h yyparse.h \
 astree.h yyparse.h
stringset.o: stringset.cpp stringset.h
astree.o: astree.cpp astree.h auxlib.h stringset.h lyutils.h yyparse.h
lyutils.o: lyutils.cpp lyutils.h astree.h auxlib.h yyparse.h
